import React from 'react';

interface AISummaryCardProps {
  summary: string | null;
  isLoading: boolean;
  error: string | null;
  onRetry: () => void;
}

const AISummaryCard: React.FC<AISummaryCardProps> = ({ summary, isLoading, error, onRetry }) => {
  if (isLoading) {
    return (
      <div className="bg-white p-6 rounded-xl shadow-md animate-pulse">
        <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold text-slate-800">✨ AI-Powered Insights</h2>
        </div>
        <div className="space-y-3">
          <div className="h-4 bg-slate-200 rounded w-3/4"></div>
          <div className="h-4 bg-slate-200 rounded w-full"></div>
          <div className="h-4 bg-slate-200 rounded w-5/6"></div>
          <div className="h-4 bg-slate-200 rounded w-1/2"></div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
        <div className="bg-red-50 border-l-4 border-red-400 p-4 rounded-r-lg shadow-md">
            <div className="flex">
                <div className="flex-shrink-0">
                    <svg className="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                    </svg>
                </div>
                <div className="ml-3">
                    <p className="text-sm font-medium text-red-800">Error Generating Summary</p>
                    <p className="mt-1 text-sm text-red-700">{error}</p>
                    <div className="mt-4">
                        <button
                            onClick={onRetry}
                            className="px-3 py-1.5 bg-red-600 text-white rounded-md text-sm font-semibold hover:bg-red-700 transition"
                        >
                            Try Again
                        </button>
                    </div>
                </div>
            </div>
      </div>
    );
  }
  
  if (!summary) return null;

  return (
    <div className="bg-white p-6 rounded-xl shadow-md animate-fade-in-slow">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold text-slate-800">✨ AI-Powered Insights</h2>
        <span className="text-xs font-medium bg-blue-100 text-blue-800 px-2 py-1 rounded-full">
          Generated by Gemini
        </span>
      </div>
      <p className="text-slate-600 whitespace-pre-wrap leading-relaxed">{summary}</p>
      <style>{`
          @keyframes fade-in-slow {
            from { opacity: 0; transform: translateY(5px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .animate-fade-in-slow {
            animation: fade-in-slow 0.5s ease-out forwards;
          }
      `}</style>
    </div>
  );
};

export default AISummaryCard;